"""Nullable False

Revision ID: 08e8ef9c4d6f
Revises: f455c5865899
Create Date: 2026-03-24 21:21:52.274824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08e8ef9c4d6f'
down_revision: Union[str, Sequence[str], None] = 'f455c5865899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE booking SET total_price = 0 WHERE total_price IS NULL"
    )
    op.alter_column('booking', 'total_price',
                    existing_type=sa.INTEGER(),
                    nullable=False)

    op.execute(
        "UPDATE booking SET created_at = NOW() WHERE created_at IS NULL"
    )
    op.alter_column('booking', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.execute(
        "UPDATE users SET is_active = True WHERE is_active IS NULL"
    )
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('booking', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('booking', 'total_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
