"""Review Added

Revision ID: 094590fffa19
Revises: 4854835e9a14
Create Date: 2026-04-14 00:48:05.261128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '094590fffa19'
down_revision: Union[str, Sequence[str], None] = '4854835e9a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('stars', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rating_sum', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rating_count', sa.BIGINT(), nullable=False),
    sa.CheckConstraint('stars >= 0 and stars <= 5', name='stars_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_types',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('type_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint("type_name <> '' AND type_name IN ('deluxe', 'family', 'general', 'suite', 'president')", name='type_name_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('h_id', sa.BIGINT(), nullable=False),
    sa.Column('room_number', sa.Text(), nullable=False),
    sa.Column('r_t_id', sa.BIGINT(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint('capacity >= 0 and capacity <= 100', name='capacity_check'),
    sa.CheckConstraint('floor >= 0', name='floor_check'),
    sa.CheckConstraint('price_per_day >= 0', name='price_per_day_check'),
    sa.ForeignKeyConstraint(['h_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['r_t_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('r_id', sa.BIGINT(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='status'), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('check_in <= check_out', name='check_in_check'),
    sa.ForeignKeyConstraint(['r_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_r_id'), 'bookings', ['r_id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('booking_id', sa.BIGINT(), nullable=False),
    sa.Column('hotel_id', sa.BIGINT(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 0 and rating <= 5', name='rating_check'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_booking_id'), 'review', ['booking_id'], unique=False)
    op.create_index(op.f('ix_review_hotel_id'), 'review', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)
    op.drop_table('booking')  # ✅ сначала booking (зависит от room)
    op.drop_table('room')  # ✅ потом room (зависит от room_type и hotel)
    op.drop_table('room_type')
    op.drop_table('hotel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stars', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('stars >= 0::numeric AND stars <= 5::numeric', name=op.f('stars_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('hotel_pkey'))
    )
    op.create_table('room_type',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("type_name <> ''::text AND (type_name = ANY (ARRAY['deluxe'::text, 'family'::text, 'general'::text, 'suite'::text, 'president'::text]))", name=op.f('type_name_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('room_type_pkey'))
    )
    op.create_table('booking',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('r_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('check_in', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_out', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint("status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'cancelled'::text, 'completed'::text])", name=op.f('status_check')),
    sa.ForeignKeyConstraint(['r_id'], ['room.id'], name=op.f('booking_r_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('booking_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_pkey'))
    )
    op.create_table('room',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('h_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('room_number', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('r_t_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_per_day', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('capacity >= 0 AND capacity <= 100', name=op.f('capacity_check')),
    sa.CheckConstraint('floor >= 0', name=op.f('floor_check')),
    sa.CheckConstraint('price_per_day >= 0::numeric', name=op.f('price_per_day_check')),
    sa.ForeignKeyConstraint(['h_id'], ['hotel.id'], name=op.f('room_h_id_fkey')),
    sa.ForeignKeyConstraint(['r_t_id'], ['room_type.id'], name=op.f('room_r_t_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('room_pkey'))
    )
    op.drop_index(op.f('ix_review_user_id'), table_name='review')
    op.drop_index(op.f('ix_review_hotel_id'), table_name='review')
    op.drop_index(op.f('ix_review_booking_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_bookings_r_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('rooms')
    op.drop_table('room_types')
    op.drop_table('hotels')
    # ### end Alembic commands ###
