"""Models Updated

Revision ID: 5d26ba2a35ea
Revises: cb36a28ee6d9
Create Date: 2026-04-20 09:16:14.292553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d26ba2a35ea'
down_revision: Union[str, Sequence[str], None] = 'cb36a28ee6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    status = postgresql.ENUM('pending', 'confirmed', 'cancelled', 'completed', name='booking_status')
    status.create(op.get_bind(), checkfirst=True)

    user_role = postgresql.ENUM('S-ADMIN', 'ADMIN', 'USER', name='user_role')
    user_role.create(op.get_bind(), checkfirst=True)


    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('method_id', sa.BIGINT(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['payment_methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("""
                TRUNCATE TABLE bookings, review, transactions
                RESTART IDENTITY CASCADE
               """)

    op.add_column('bookings', sa.Column('guest_count', sa.Integer(), nullable=False))
    op.execute("UPDATE bookings SET guest_count = 1 WHERE guest_count IS NULL;")
    op.alter_column('bookings', 'guest_count', existing_type=sa.Integer(), nullable=False, server_default='1')

    op.alter_column('bookings', 'status',
               existing_type=sa.TEXT(),
               type_=status,
               existing_nullable=False,
               postgresql_using='status::text::booking_status',
                    )

    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.drop_constraint(op.f('bookings_r_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_user_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'rooms', ['r_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('hotels', sa.Column('policy_id', sa.BIGINT(), nullable=True))
    op.alter_column('hotels', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('hotels', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('hotels', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('hotels', 'rating_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_hotels_city'), 'hotels', ['city'], unique=False)
    op.create_index(op.f('ix_hotels_name'), 'hotels', ['name'], unique=False)
    op.create_foreign_key(None, 'hotels', 'cancellation_policy', ['policy_id'], ['id'])
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('review_user_id_fkey'), 'review', type_='foreignkey')
    op.drop_constraint(op.f('review_booking_id_fkey'), 'review', type_='foreignkey')
    op.drop_constraint(op.f('review_hotel_id_fkey'), 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('room_types', 'type_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_unique_constraint(None, 'room_types', ['type_name'])
    op.alter_column('rooms', 'room_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('rooms', 'r_t_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_rooms_h_id'), 'rooms', ['h_id'], unique=False)
    op.create_index(op.f('ix_rooms_r_t_id'), 'rooms', ['r_t_id'], unique=False)
    op.drop_constraint(op.f('rooms_h_id_fkey'), 'rooms', type_='foreignkey')
    op.drop_constraint(op.f('rooms_r_t_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'room_types', ['r_t_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'rooms', 'hotels', ['h_id'], ['id'], ondelete='CASCADE')
    op.add_column('transactions', sa.Column('payment_id', sa.BIGINT(), nullable=True))
    op.alter_column('transactions', 'type',
               existing_type=postgresql.ENUM('PAYMENT', 'REFUND', 'PENALTY', name='type'),
               nullable=False)
    op.create_index(op.f('ix_transactions_payment_id'), 'transactions', ['payment_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'payments', ['payment_id'], ['id'])
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=100),
               type_=user_role,
               existing_nullable=False,
               postgresql_using='role::text::user_role',
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('S-ADMIN', 'ADMIN', 'USER', name='user_role', create_constraint=True),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_payment_id'), table_name='transactions')
    op.alter_column('transactions', 'type',
               existing_type=postgresql.ENUM('PAYMENT', 'REFUND', 'PENALTY', name='type'),
               nullable=True)
    op.drop_column('transactions', 'payment_id')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_r_t_id_fkey'), 'rooms', 'room_types', ['r_t_id'], ['id'])
    op.create_foreign_key(op.f('rooms_h_id_fkey'), 'rooms', 'hotels', ['h_id'], ['id'])
    op.drop_index(op.f('ix_rooms_r_t_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_h_id'), table_name='rooms')
    op.alter_column('rooms', 'r_t_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('rooms', 'room_number',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'room_types', type_='unique')
    op.alter_column('room_types', 'type_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(op.f('review_hotel_id_fkey'), 'review', 'hotels', ['hotel_id'], ['id'])
    op.create_foreign_key(op.f('review_booking_id_fkey'), 'review', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key(op.f('review_user_id_fkey'), 'review', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'hotels', type_='foreignkey')
    op.drop_index(op.f('ix_hotels_name'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_city'), table_name='hotels')
    op.alter_column('hotels', 'rating_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('hotels', 'address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('hotels', 'city',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('hotels', 'name',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('hotels', 'policy_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_user_id_fkey'), 'bookings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('bookings_r_id_fkey'), 'bookings', 'rooms', ['r_id'], ['id'])
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'cancelled', 'completed', name='booking_status', create_constraint=True),
               type_=sa.TEXT(),
               existing_nullable=False,
               postgresql_using='status::text',
                    )
    op.drop_column('bookings', 'guest_count')
    op.execute("""
               TRUNCATE TABLE bookings, review, transactions
                RESTART IDENTITY CASCADE
               """)
    op.drop_table('payments')
    op.drop_table('payment_methods')
    status = postgresql.ENUM('pending', 'confirmed', 'cancelled', 'completed', name='booking_status', create_constraint=True)
    status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
