"""update models

Revision ID: 99a499d19088
Revises: db2b335647ff
Create Date: 2026-03-11 14:28:37.946192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a499d19088'
down_revision: Union[str, Sequence[str], None] = 'db2b335647ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('room', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'description')
    op.drop_column('hotel', 'description')
    # ### end Alembic commands ###
