"""ADD policy, transaction

Revision ID: cb36a28ee6d9
Revises: bee7af1b6039
Create Date: 2026-04-15 01:07:15.842913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb36a28ee6d9'
down_revision: Union[str, Sequence[str], None] = 'bee7af1b6039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellation_policy',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hours_before', sa.Integer(), nullable=False),
    sa.Column('penalty_percent', sa.Integer(), nullable=False),
    sa.CheckConstraint('hours_before >= 0', name='hours_before_check'),
    sa.CheckConstraint('penalty_percent >= 0', name='penalty_percent_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('booking_id', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.Enum('PAYMENT', 'REFUND', 'PENALTY', name='type'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_booking_id'), 'transactions', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_booking_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('cancellation_policy')
    # ### end Alembic commands ###
