"""Updated Model Booking, User

Revision ID: f455c5865899
Revises: d3613db7a31d
Create Date: 2026-03-24 21:19:05.957758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f455c5865899'
down_revision: Union[str, Sequence[str], None] = 'd3613db7a31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('total_price', sa.Integer(), nullable=True))
    op.add_column('booking', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('booking', 'created_at')
    op.drop_column('booking', 'total_price')
    # ### end Alembic commands ###
